### ISSUE TITLE
Sampling quality is bad.

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#13]
I trained my model on high-quality data for 280,000 steps and during evaluation, the model had a really bad sense of the context and the generated replies were pretty poor. I'm gonna give a shot to https://github.com/nshepperd/gpt-2 to see if it's a problem in your code or something that I did. I thoough it would be good to share my experience.

**Comment by Mrpatekful** [comment]
Yes I have noticed and I have been working on this problem for a long time. This is the reason that I have not yet provided any example results. As soon as this is resolved I will update the repository with trained weights and example responses.

**Comment by dimeldo** [comment]
👍 
Probably a good idea to put a notice for that in the README until it is resolved.
