### ISSUE TITLE
Problem relating to max_hist or max_len

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#15]
Hello, I'm getting this error which seems to be related either to `max_hist` or `max_len`. I can't point to which but changing them to lower values make training goes alright, and higher values (max_hist=10, max_len=1000, for example) raise the error.

```
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = c10::Half, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [108,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = c10::Half, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [108,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = c10::Half, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [108,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
....
....
```

Training seems to continue regularly but I'm not sure if everything's sound.

**Comment by Mrpatekful** [comment]
Those numbers are edge cases. `max_hist` value of 10 means there are 10 previous utterances which are fed as input to the transformer and 1000 `max_len` is the length of each utterance. At worst case this means a 10000 + len(target) number of inputs to the model. Most transformer models have a fixed positional encoding layer, which constrains the length of input to a maximum value ( typically ~500 ). Now at the beginning of training the model is checked against the longest possible sequence with the current batch size to detect any possible memory error before training ( preventing deadlocks from exceptions during distributed multi gpu sessions ) and the message you are seeing is probably related to this. I am guessing you are using a GPU session, which emits a warning message, however if you were using a CPU session you would probably receive an exception regarding this problem.

**Comment by dimeldo** [comment]
Oh ok, thanks for the clarification. I thought max_len is the max length of the entire dialogue.

**Comment by dimeldo** [comment]
Is it ok to ignore this warning? Will the model read the dialogues with the maximum length specified? Or will it truncate them? Or just make gibberish out of it?

**Comment by dimeldo** [comment]
Can I increase the maximum value of the positional encoding layer?

**Comment by Mrpatekful** [comment]
The parameters of the models are determined by the configs from the transformers/huggingface library. Theoretically you could modify the positional embedding layer, but this project does not provide a way to do it. The model can only read sequences of length `n_positions` which is specified in the model config, that is 1024 in case of the gpt-2 model. I think you should definitely lower the input length, to a point where there arent any warnings.

**Comment by dimeldo** [comment]
Ok. So how did Open-AI generated such long texts if the model was only trained at a maximum length of 1024? If it's a trick in the generation process, still, by not learning such long texts how was it able to do so in a good way?

**Comment by Mrpatekful** [comment]
To my knowledge they simply use a sliding window, so the model output is only conditioned on the last 1024 tokens. The result is still good because a sequence of length 1000 is enough to provide the neccessary context for the model to be seemingly consistent.

**Comment by Mrpatekful** [comment]
Transformer XL for example improves this by having a recurrent connection in the model, thus enabling it to use knowledge from longer sequences as well.

**Comment by dimeldo** [comment]
Gotcha, thanks for taking the time to provide this information. Keep up the good job with this repo 👍
