### ISSUE TITLE
Loading metadata stuck on distributed machine

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#3]
I'm trying to run your model on a machine with 8 Nvidia V100 GPUs.
I used this command:

`torch.distributed.init_process_group(
            backend='nccl', init_method='env://', rank=args.local_rank, world_size=8)`

Where local_rank is set to 1. But it gets stuck on:

`Loading metadata from ./data/dailydialog/xlnet/metadata.json`

How can I resolve this, please?

**Comment by Mrpatekful** [comment]
I don't currently have access to multi-gpu machine, but I will look into it in a few days.

**Comment by dimeldo** [comment]
Working (:
