### ISSUE TITLE
Update GPT-2 model to 774M

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#5]
12 hours ago, OpenAI [released](https://openai.com/blog/gpt-2-6-month-follow-up/) their GPT-2 774M pre-trained model through their [commit on GitHub](https://github.com/openai/gpt-2/commit/f35fa1d920e9d2d0690f66d03aa3f76b3c59230e). Can you please update this repository to use that model? It is more powerful than the current GPT-2 355M pre-trained model.

**Comment by ricsinaruto** [comment]
I think the plan is to wait for huggingface to integrate it and then use it here. Feel free to contribute if you want 😄

**Comment by dimeldo** [comment]
Thanks!
