### ISSUE TITLE
Issue with latest merge [torch.distributed]

### ISSUE THREAD

**Issue by zbloss** [bme-chatbots/dialogue-generation#9]
When running the run.py script with torch==1.2.0 I get the following error:

`Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from src.train import (
  File "C:\Users\altoz\Documents\Projects\dialogue-generation\src\train.py", line 50, in <module>
    from torch.distributed import all_reduce, reduce_op
ImportError: cannot import name 'all_reduce'`

**Comment by Mrpatekful** [comment]
There might be something wrong with your Python environment. I am using virtualenv with python 3.6, torch 1.2 and it is running fine.
